terminal:
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: rgba(38, 50, 56, 1)
    selection: null
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - rgba(255, 255, 255, 0.2)
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  environment: {}
  font: source han code jp
  ligatures: true
  background: theme
  fontSize: 14
  frontend: xterm-webgl
  searchOptions: {}
  cursorBlink: true
  profiles:
    - name: Git-Bash
      shell: git-bash
      sessionOptions:
        command: C:\Program Files\Git\bin\bash.exe
        args:
          - '--login'
          - '-i'
        env:
          TERM: cygwin
    - name: WSL / Default distro
      shell: wsl
      sessionOptions:
        command: C:\WINDOWS\system32\wsl.exe
        args:
          - '~'
        env:
          TERM: xterm-color
          COLORTERM: truecolor
  fallbackFont: Cica
  profile: default-(wsl-/-default-distro)
  workingDirectory: ~/
  pasteOnMiddleClick: false
  recoverTabs: false
hotkeys:
  shell: {}
  profile: {}
  toggle-window: []
serial: {}
ssh: {}
appearance:
  vibrancyType: blur
  theme: Standard
  opacity: 1
  vibrancy: true
enableWelcomeTab: false
pluginBlacklist: []
enableAutomaticUpdates: false
